routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//WEB
Route::get('/', function () {
    return redirect(route('product.index'));
});
Illuminate\Support\Facades\Auth::routes();
Route::middleware('auth')->group(function () {
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
});
Route::middleware('user')->group(function () {
    Route::resource('cart', App\Http\Controllers\CartController::class)->except('index', 'show', 'create', 'edit');
    Route::resource('transaction', App\Http\Controllers\TransactionController::class)->only('index', 'store');
});
Route::get('product/type/{type}', [App\Http\Controllers\SubProductController::class, 'productType'])->name('product.type');
Route::get('product/brands/{brand}', [App\Http\Controllers\SubProductController::class, 'productBrand'])->name('product.brand');
// Route::get('product/color/{productColor}', [App\Http\Controllers\SubProductController::class, 'productColor'])->name('product.color');
Route::resource('product', App\Http\Controllers\ProductController::class);
Route::middleware('admin')->group(function () {
    Route::get('brand', [App\Http\Controllers\BrandController::class, 'index']);
    Route::get('payment', [App\Http\Controllers\PaymentMethodController::class, 'index']);
    Route::get('delivery', [App\Http\Controllers\DeliveryController::class, 'index']);
    Route::get('type', [App\Http\Controllers\TypeController::class, 'index']);
    Route::get('color', [App\Http\Controllers\ProductColorController::class, 'index']);
});




//API
Route::middleware('auth')->group(function () {
});
Route::middleware('user')->group(function () {
    Route::apiResource('api/address', \App\Http\Controllers\Api\AddressController::class);
    Route::get('api/province', [\App\Http\Controllers\Api\RajaOngkir::class, 'province']);
    Route::get('api/city/{province}', [\App\Http\Controllers\Api\RajaOngkir::class, 'city']);
    Route::post('api/cost', [\App\Http\Controllers\Api\RajaOngkir::class, 'cost'])->name('raja.cost');
});
Route::middleware('admin')->group(function () {
    Route::apiResource('api/type', \App\Http\Controllers\Api\TypeController::class);
    Route::apiResource('api/brand', \App\Http\Controllers\Api\BrandController::class);
    Route::apiResource('api/payment', \App\Http\Controllers\Api\PaymentController::class);
    Route::apiResource('api/delivery', \App\Http\Controllers\Api\DeliveryController::class);
    Route::apiResource('api/color', \App\Http\Controllers\Api\ProductColorController::class);
});

resources/views/admin/layouts/app.blade.php
<!DOCTYPE html>
<html class="loading" lang="en" data-textdirection="ltr">
<!-- BEGIN: Head-->
@include('admin.layouts.head')
<!-- END: Head-->

<!-- BEGIN: Body-->

<body class="vertical-layout vertical-menu-modern  navbar-floating footer-static  " data-open="click" data-menu="vertical-menu-modern" data-col="">

    <!-- BEGIN: Header-->
    @include('admin.layouts.nav')
    <!-- END: Header-->
    <!-- BEGIN: Main Menu-->
    @include('admin.layouts.sidebar')
    <!-- END: Main Menu-->
    <!-- BEGIN: Content-->
    @yield('content')
    <!-- END: Content-->
    <div class="sidenav-overlay"></div>
    <div class="drag-target"></div>
    <!-- BEGIN: Footer-->
    {{-- @include('admin.layouts.footer') --}}
    <!-- END: Footer-->
    <div class="js">
        @include('admin.layouts.js')
    </div>
</body>
<!-- END: Body-->

</html>

resources/views/admin/layouts/footer.blade.php
<footer class="footer footer-static footer-light">
        <p class="clearfix mb-0"><span class="float-md-left d-block d-md-inline-block mt-25">COPYRIGHT &copy; 2020<a class="ml-25" href="https://1.envato.market/pixinvent_portfolio" target="_blank">Pixinvent</a><span class="d-none d-sm-inline-block">, All rights Reserved</span></span><span class="float-md-right d-none d-md-block">Hand-crafted & Made with<i data-feather="heart"></i></span></p>
    </footer>
    <button class="btn btn-primary btn-icon scroll-top" type="button"><i data-feather="arrow-up"></i></button>

resources/views/admin/layouts/head.blade.php
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta name="description" content="Vuexy admin is super flexible, powerful, clean &amp; modern responsive bootstrap 4 admin template with unlimited possibilities.">
    <meta name="keywords" content="admin template, Vuexy admin template, dashboard template, flat admin template, responsive admin template, web app">
    <meta name="author" content="PIXINVENT">
    <title>@yield('title')</title>
    <link rel="apple-touch-icon" href="{{ asset('assets') }}/admin/images/ico/apple-icon-120.png">
    <link rel="shortcut icon" type="image/x-icon" href="{{ asset('assets') }}/admin/images/ico/favicon.ico">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,300;0,400;0,500;0,600;1,400;1,500;1,600" rel="stylesheet">
    
    <!-- BEGIN: Vendor CSS-->
    <link rel="stylesheet" type="text/css" href="{{ asset('assets') }}/admin/vendors/css/vendors.min.css">
    <link rel="stylesheet" type="text/css" href="{{ asset('assets') }}/admin/vendors/css/charts/apexcharts.css">
    <link rel="stylesheet" type="text/css" href="{{ asset('assets') }}/admin/vendors/css/extensions/toastr.min.css">
    <link rel="stylesheet" type="text/css" href="{{ asset('assets') }}/admin/vendors/css/extensions/sweetalert2.min.css">
    <link rel="stylesheet" type="text/css" href="{{ asset('assets') }}/admin/vendors/css/forms/wizard/bs-stepper.min.css">
    <link rel="stylesheet" type="text/css" href="{{ asset('assets') }}/admin/vendors/css/forms/spinner/jquery.bootstrap-touchspin.css">
    <!-- END: Vendor CSS-->

    <!-- BEGIN: Theme CSS-->
    <link rel="stylesheet" type="text/css" href="{{ asset('assets') }}/admin/css/bootstrap.css">
    <link rel="stylesheet" type="text/css" href="{{ asset('assets') }}/admin/css/bootstrap-extended.css">
    <link rel="stylesheet" type="text/css" href="{{ asset('assets') }}/admin/css/colors.css">
    <link rel="stylesheet" type="text/css" href="{{ asset('assets') }}/admin/css/components.css">
    <link rel="stylesheet" type="text/css" href="{{ asset('assets') }}/admin/css/themes/dark-layout.css">
    <link rel="stylesheet" type="text/css" href="{{ asset('assets') }}/admin/css/themes/bordered-layout.css">
    <link rel="stylesheet" type="text/css" href="{{ asset('assets') }}/admin/css/themes/semi-dark-layout.css">

    <!-- BEGIN: Page CSS-->
    @stack('pagecss')
    <link rel="stylesheet" type="text/css" href="{{ asset('assets') }}/admin/css/core/menu/menu-types/vertical-menu.css">
    <link rel="stylesheet" type="text/css" href="{{ asset('assets') }}/admin/css/pages/dashboard-ecommerce.css">
    <link rel="stylesheet" type="text/css" href="{{ asset('assets') }}/admin/css/plugins/charts/chart-apex.css">
    <link rel="stylesheet" type="text/css" href="{{ asset('assets') }}/admin/css/plugins/extensions/ext-component-toastr.css">
    <link rel="stylesheet" type="text/css" href="{{ asset('assets') }}/admin/css/select2.min.css">
    <!-- END: Page CSS-->

    <!-- BEGIN: Custom CSS-->
    @stack('styles')
    <!-- END: Custom CSS-->

</head>

resources/views/admin/layouts/js.blade.php
<!-- BEGIN: Vendor JS-->
    <script src="{{ asset('assets') }}/admin/vendors/js/vendors.min.js"></script>
    <!-- BEGIN Vendor JS-->

    <!-- BEGIN: Page Vendor JS-->
    <script src="{{ asset('assets') }}/admin/vendors/js/charts/apexcharts.min.js"></script>
    <script src="{{ asset('assets') }}/admin/vendors/js/extensions/toastr.min.js"></script>
    <script src="{{ asset('assets') }}/admin/vendors/js/extensions/sweetalert2.all.min.js"></script>
    
    <script src="{{ asset('assets') }}/admin/vendors/js/forms/wizard/bs-stepper.min.js"></script>
    <script src="{{ asset('assets') }}/admin/vendors/js/forms/spinner/jquery.bootstrap-touchspin.js"></script>
    <!-- END: Page Vendor JS-->

    <!-- BEGIN: Theme JS-->
    <script src="{{ asset('assets') }}/admin/js/core/app-menu.js"></script>
    <script src="{{ asset('assets') }}/admin/js/core/app.js"></script>
    <!-- END: Theme JS-->

    <!-- BEGIN: Page JS-->
    @stack('pagejs')
    {{-- <script src="{{ asset('assets') }}/admin/js/scripts/pages/dashboard-ecommerce.js"></script> --}}
    <script src="{{ asset('assets') }}/admin/js/select2.full.min.js"></script>
    <!-- END: Page JS-->
    <script src="{{ asset('js/myFunc.js') }}"></script>
    <script>
    $(document).ready(function () {
        // UPDATE BUTTON
        $(document).on('keyup', '#quantity', function () {
            var id = $(this).data('id');
            var pId = $(this).data('product');
            var qty = $(this).val();
            if(qty >= 0){
                $.ajax({
                    'url': '{{url('cart')}}/' + id,
                    'type': 'POST',
                    'data': {
                        'id': id,
                        'qty': qty,
                        'type': 3,
                        '_method': 'PUT',
                        '_token': '{{csrf_token()}}',
                    },
                    success: function (response) {
                        if (response == 1) {
                            toastr.error('Data Gagal ditambah!', 'Gagal!', {
                                closeButton: true,
                                tapToDismiss: true
                            });
                        } else {
                        }
                    }
                });
            } else{ 
                console.log('gagal');
            }
        });
        const inQuantity = document.querySelectorAll('#quantity');
        inQuantity.forEach(qty => {
            $(qty).on('change', function () {
                $(qty).TouchSpin({
                    'max': 100,
                    'min': 1,
                })
                if ($(qty).val() == 0) {
                    $(qty).val(1);
                }
            });
        });
        const delBtn = document.querySelectorAll('#btn-del-cart');
        delBtn.forEach(del => {
            $(del).click(function () {
                var id = $(this).data('id');
                Swal.fire({
                    icon: 'error',
                    title: 'Are you sure?',
                    text: "You won't be able to revert this!",
                    type: 'error',
                    showCancelButton: true,
                    confirmButtonColor: '#28C76F',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Yes, delete it!'
                })
                .then((result) => {
                    if (result.value) {
                        $(this).parents('.media.align-items-center').remove();
                        $.ajax({
                            'url': '{{url('cart')}}/' + id,
                            'type': 'POST',
                            'data': {
                                '_method': 'DELETE',
                                '_token': '{{csrf_token()}}',
                            },
                            success: function (data) {
                                toastr.success('Data Berhasi dihapus', 'Berhasil!', {
                                    closeButton: true,
                                    tapToDismiss: true
                                });
                                if (data.cart_count == null) {
                                    data.cart_count = 0;
                                }
                                $('#cart-itemss').text(data.cart_count + ' Items');
                                $('#bulet').text(data.cart_count);
                                var rowsEmpty = '';
                                if (data.cart_count == 0) {
                                    $('#total-note').attr('class', '');
                                    $('#total-note').html('');
                                    rowsEmpty += '<div id="empty-note" class="media align-items-center">'+
                                                    '<div class="media-body d-flex justify-content-center">'+
                                                        '<p class="text-danger">Cart is empty</p>'+
                                                    '</div>'+
                                                '</div>';
                                }
                                $('#empty-note').html(rowsEmpty);
                            }
                        });
                    } else {
                        toastr['error']('Failed add to cart!', 'Failed',{
                            closeButton: true,
                            tapToDismiss: true
                            });
                    }
                });
            }); 
        });
        
        // UPDATE INPUT
        $(document).on('change', '#quantity', function () {
            var id = $(this).data('id');
            var qty = $(this).val();
            var thisIs = $(this);
            $.ajax({
                'url': '{{url('cart')}}/' + id,
                'type': 'POST',
                'data': {
                    'id': id,
                    'qty': qty,
                    '_method': 'PUT',
                    '_token': '{{csrf_token()}}',
                },
                success: function (data) {
                        $('#total').text('Rp. ' + number_format(data.total));
                        var prices = thisIs.parents('div.media-body');
                        prices.find('#price-item').text('Rp. ' + number_format(data.cart.price_total));
                }
            });
        });
    });
    </script>
    @stack('script')
    @stack('scripts')
    <script>
        $(window).on('load', function() {
            if (feather) {
                feather.replace({
                    width: 14,
                    height: 14
                });
            }
        })
    </script>

resources/views/admin/layouts/sidebar.blade.php
<div class="main-menu menu-fixed menu-light menu-accordion menu-shadow" data-scroll-to-active="true">
        <div class="navbar-header">
            <ul class="nav navbar-nav flex-row">
                <li class="nav-item mr-auto"><a class="navbar-brand" href="{{ asset('assets') }}/admin/html/ltr/vertical-menu-template/index.html"><span class="brand-logo">
                            <svg viewbox="0 0 139 95" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" height="24">
                                <defs>
                                    <lineargradient id="linearGradient-1" x1="100%" y1="10.5120544%" x2="50%" y2="89.4879456%">
                                        <stop stop-color="#000000" offset="0%"></stop>
                                        <stop stop-color="#FFFFFF" offset="100%"></stop>
                                    </lineargradient>
                                    <lineargradient id="linearGradient-2" x1="64.0437835%" y1="46.3276743%" x2="37.373316%" y2="100%">
                                        <stop stop-color="#EEEEEE" stop-opacity="0" offset="0%"></stop>
                                        <stop stop-color="#FFFFFF" offset="100%"></stop>
                                    </lineargradient>
                                </defs>
                                <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                    <g id="Artboard" transform="translate(-400.000000, -178.000000)">
                                        <g id="Group" transform="translate(400.000000, 178.000000)">
                                            <path class="text-primary" id="Path" d="M-5.68434189e-14,2.84217094e-14 L39.1816085,2.84217094e-14 L69.3453773,32.2519224 L101.428699,2.84217094e-14 L138.784583,2.84217094e-14 L138.784199,29.8015838 C137.958931,37.3510206 135.784352,42.5567762 132.260463,45.4188507 C128.736573,48.2809251 112.33867,64.5239941 83.0667527,94.1480575 L56.2750821,94.1480575 L6.71554594,44.4188507 C2.46876683,39.9813776 0.345377275,35.1089553 0.345377275,29.8015838 C0.345377275,24.4942122 0.230251516,14.560351 -5.68434189e-14,2.84217094e-14 Z" style="fill:currentColor"></path>
                                            <path id="Path1" d="M69.3453773,32.2519224 L101.428699,1.42108547e-14 L138.784583,1.42108547e-14 L138.784199,29.8015838 C137.958931,37.3510206 135.784352,42.5567762 132.260463,45.4188507 C128.736573,48.2809251 112.33867,64.5239941 83.0667527,94.1480575 L56.2750821,94.1480575 L32.8435758,70.5039241 L69.3453773,32.2519224 Z" fill="url(#linearGradient-1)" opacity="0.2"></path>
                                            <polygon id="Path-2" fill="#000000" opacity="0.049999997" points="69.3922914 32.4202615 32.8435758 70.5039241 54.0490008 16.1851325"></polygon>
                                            <polygon id="Path-21" fill="#000000" opacity="0.099999994" points="69.3922914 32.4202615 32.8435758 70.5039241 58.3683556 20.7402338"></polygon>
                                            <polygon id="Path-3" fill="url(#linearGradient-2)" opacity="0.099999994" points="101.428699 0 83.0667527 94.1480575 130.378721 47.0740288"></polygon>
                                        </g>
                                    </g>
                                </g>
                            </svg></span>
                        <h2 class="brand-text">Clock</h2>
                    </a></li>
                <li class="nav-item nav-toggle"><a class="nav-link modern-nav-toggle pr-0" data-toggle="collapse"><i class="d-block d-xl-none text-primary toggle-icon font-medium-4" data-feather="x"></i><i class="d-none d-xl-block collapse-toggle-icon font-medium-4  text-primary" data-feather="disc" data-ticon="disc"></i></a></li>
            </ul>
        </div>
        <div class="shadow-bottom"></div>
        <div class="main-menu-content">
            <ul class="navigation navigation-main" id="main-menu-navigation" data-menu="menu-navigation">
                @auth
                    <li class="@yield('home') nav-item"><a class="d-flex align-items-center" href="{{ route('home') }}"><i data-feather="home"></i><span class="menu-title text-truncate" data-i18n="Dashboards">Dashboards</span></a>
                    </li>
                @endauth
                <li class=" navigation-header"><span>Product</span><i data-feather="more-horizontal"></i>
                </li>
                <li class="nav-item has-sub">
                    <a class="d-flex align-items-center" href="#"><i data-feather="box"></i><span class="menu-title text-truncate" data-i18n="product">Product</span>
                    </a>
                    <ul class="menu-content">
                        <li class="@yield('product')">
                            <a class="d-flex align-items-center" href="{{ route('product.index') }}"><i data-feather="box"></i><span class="menu-title text-truncate" data-i18n="all-product">All Product</span>
                            </a>
                        </li>
                        <li class="nav-item has-sub">
                            <a class="d-flex align-items-center" href="#"><i data-feather="box"></i><span class="menu-title text-truncate" data-i18n="product">Product By Type</span></a>
                            <ul class="menu-content">
                                @foreach ($types as $type)
                                @php
                                    $urlType =  $_SERVER["REQUEST_URI"];
                                    $urlType = collect(str_split($urlType));
                                    $urlType = $urlType->splice(14)->implode('');
                                @endphp
                                <li class="{{ $type->id == $urlType ? 'active' : ''}}">
                                    <a class="d-flex align-items-center" href="{{ route('product.type', $type) }}"><i data-feather="box"></i><span class="menu-title text-truncate" data-i18n="product-type">{{ $type->type }}</span>
                                    </a>
                                </li>
                                @endforeach
                            </ul>
                        </li>
                        <li class="nav-item has-sub">
                            <a class="d-flex align-items-center" href="#"><i data-feather="box"></i><span class="menu-title text-truncate" data-i18n="product">Product By Brand</span></a>
                            <ul class="menu-content">
                                @foreach ($brands as $brand)
                                @php
                                    $urlBrand =  $_SERVER["REQUEST_URI"];
                                    $urlBrand = collect(str_split($urlBrand));
                                    $urlBrand = $urlBrand->splice(16)->implode('');
                                    $nav = 'brand'.$loop->iteration;
                                    $urlBrand = 'brand'.$urlBrand;
                                @endphp
                                <li class="{{ $nav == $urlBrand ? 'active' : '' }}">
                                    <a class="d-flex align-items-center" href="{{ route('product.brand', $brand) }}"><i data-feather="box"></i><span class="menu-title text-truncate" data-i18n="product-brand">{{ $brand->brand_name }}</span>
                                    </a>
                                </li>
                                @endforeach
                            </ul>
                        </li>
                        {{-- <li class="nav-item has-sub">
                            <a class="d-flex align-items-center" href="#"><i data-feather="box"></i><span class="menu-title text-truncate" data-i18n="product">Product By Color</span></a>
                            <ul class="menu-content">
                                @foreach ($colors as $color)
                                @php
                                    $urlColor =  $_SERVER["REQUEST_URI"];
                                    $urlColor = collect(str_split($urlColor));
                                    $urlColor = $urlColor->splice(15)->implode('');
                                    $nav = 'color'.$loop->iteration;
                                    $urlColor = 'color'.$urlColor;
                                @endphp
                                <li class="{{ $nav == $urlColor ? 'active' : '' }}">
                                    <a class="d-flex align-items-center" href="{{ route('product.color', $color) }}"><i data-feather="box"></i><span class="menu-title text-truncate" data-i18n="product-brand">{{ $color->color_name }}</span>
                                    </a>
                                </li>
                                @endforeach
                            </ul>
                        </li> --}}
                    </ul>
                </li>
                @can('user')
                    <li class=" navigation-header"><span>Transaction</span><i data-feather="more-horizontal"></i>
                    </li>
                    <li class="@yield('transaction') nav-item">
                        <a class="d-flex align-items-center" href="{{ route('transaction.index') }}"><i data-feather="dollar-sign"></i><span class="menu-title text-truncate" data-i18n="product">Transaction</span>
                        </a>
                    </li>
                @endcan
                </li>
                @can('admin')
                <li class="@yield('brand') nav-item"><a class="d-flex align-items-center" href="{{ url('brand') }}"><i data-feather="tag"></i><span class="menu-title text-truncate" data-i18n="brand">Brand</span></a>
                </li>
                <li class="@yield('type') nav-item"><a class="d-flex align-items-center" href="{{ url('type') }}"><i data-feather="type"></i><span class="menu-title text-truncate" data-i18n="type">Type</span></a>
                </li>
                <li class="@yield('color') nav-item"><a class="d-flex align-items-center" href="{{ url('color') }}"><i data-feather="droplet"></i><span class="menu-title text-truncate" data-i18n="type">Color</span></a>
                </li>
                <li class="@yield('delivery') nav-item"><a class="d-flex align-items-center" href="{{ url('delivery') }}"><i data-feather="package"></i><span class="menu-title text-truncate" data-i18n="type">Delivery</span></a>
                </li>
                <li class="@yield('payment') nav-item"><a class="d-flex align-items-center" href="{{ url('payment') }}"><i data-feather="dollar-sign"></i><span class="menu-title text-truncate" data-i18n="type">Payment Method</span></a>
                </li>
                {{-- <li class="@yield('stock') nav-item"><a class="d-flex align-items-center" href="{{ route('stock.index') }}"><i data-feather="droplet"></i><span class="menu-title text-truncate" data-i18n="type">Product Stock</span></a>
                </li> --}}
                @endcan
                
                
        </div>
</div>