routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//WEB
Route::get('/', function () {
    return redirect(route('product.index'));
});
Illuminate\Support\Facades\Auth::routes();
Route::middleware('auth')->group(function () {
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
});
Route::middleware('user')->group(function () {
    Route::resource('cart', App\Http\Controllers\CartController::class)->except('index', 'show', 'create', 'edit');
    Route::resource('transaction', App\Http\Controllers\TransactionController::class)->only('index', 'store');
});
Route::get('product/type/{type}', [App\Http\Controllers\SubProductController::class, 'productType'])->name('product.type');
Route::get('product/brands/{brand}', [App\Http\Controllers\SubProductController::class, 'productBrand'])->name('product.brand');
// Route::get('product/color/{productColor}', [App\Http\Controllers\SubProductController::class, 'productColor'])->name('product.color');
Route::resource('product', App\Http\Controllers\ProductController::class);
Route::middleware('admin')->group(function () {
    Route::get('brand', [App\Http\Controllers\BrandController::class, 'index']);
    Route::get('payment', [App\Http\Controllers\PaymentMethodController::class, 'index']);
    Route::get('delivery', [App\Http\Controllers\DeliveryController::class, 'index']);
    Route::get('type', [App\Http\Controllers\TypeController::class, 'index']);
    Route::get('color', [App\Http\Controllers\ProductColorController::class, 'index']);
});




//API
Route::middleware('auth')->group(function () {
});
Route::middleware('user')->group(function () {
    Route::apiResource('api/address', \App\Http\Controllers\Api\AddressController::class);
    Route::get('api/province', [\App\Http\Controllers\Api\RajaOngkir::class, 'province']);
    Route::get('api/city/{province}', [\App\Http\Controllers\Api\RajaOngkir::class, 'city']);
    Route::post('api/cost', [\App\Http\Controllers\Api\RajaOngkir::class, 'cost'])->name('raja.cost');
});
Route::middleware('admin')->group(function () {
    Route::apiResource('api/type', \App\Http\Controllers\Api\TypeController::class);
    Route::apiResource('api/brand', \App\Http\Controllers\Api\BrandController::class);
    Route::apiResource('api/payment', \App\Http\Controllers\Api\PaymentController::class);
    Route::apiResource('api/delivery', \App\Http\Controllers\Api\DeliveryController::class);
    Route::apiResource('api/color', \App\Http\Controllers\Api\ProductColorController::class);
});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;

    protected $guarded = ['id'];

    public function type()
    {
        return $this->belongsTo(Type::class);
    }
    public function brand()
    {
        return $this->belongsTo(Brand::class);
    }
    public function detail()
    {
        return $this->hasOne(ProductDetails::class);
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Models\Cart;
use App\Models\Type;
use App\Models\Brand;
use App\Models\Total;
use App\Models\Product;
use App\Models\ProductColor;
use Illuminate\Http\Request;
use App\Models\ProductColorDetailsPivot;
use App\Models\ProductDetails;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;

class ProductController extends Controller
{
    public function __construct()
    {
        $this->middleware('admin')->except(['index', 'show']);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.product.list', [
            'products' => Product::with(['type', 'brand', 'detail'])->latest()->paginate(3),
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        return view('admin.product.form', [
            'colors' => ProductColor::all(),
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'product_name' => 'required',
            'brand_id' => 'required',
            'type_id' => 'required',
            'price' => 'required',
            'stock' => 'required',
            'description' => 'required',
            'product_image' => 'image|file|mimes:png,jpg,jpeg|max:2048'
        ]);
        $data = [
            'product_name' => $request->product_name,
            'brand_id' => $request->brand_id,
            'type_id' => $request->type_id
        ];
        $detail = [
            'price' => $request->price,
            'stock' => $request->stock,
            'description' => $request->description,
            'product_image' => $request->product_image
        ];
        if ($request->hasFile('product_image')) {
            $detail['product_image'] = $request->file('product_image')->store('product-image');
        } else {
            $detail['product_image'] = 'product-image/NoImg.png';
        };
        $productCreate = Product::create($data);
        $productDetailsCreate = ProductDetails::create([
            'product_id' => $productCreate->id,
            'price' => $request->price,
            'stock' => $request->stock,
            'weight' => 1000,
            'description' => $request->description,
            'product_image' => $detail['product_image']
        ]);
        $colors = $request->color;
        foreach ($colors as $color) {
            ProductColorDetailsPivot::create([
                'product_details_id' => $productDetailsCreate->id,
                'product_color_id' => $color,
            ]);
        }
        return redirect(route('product.index'))->with('success', 'Successfully Added Product');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        return view('admin.product.detail', [
            'product' => $product->find($product->id)
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        return view('admin.product.form', [
            'product' => $product,
            'colors' => ProductColor::all(),
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {
        $request->validate([
            'product_name' => 'required',
            'brand_id' => 'required',
            'type_id' => 'required',
            'price' => 'required',
            'stock' => 'required',
            'description' => 'required',
            'product_image' => 'image|file|mimes:png,jpg,jpeg|max:2048'
        ]);
        $data = [
            'product_name' => $request->product_name,
            'brand_id' => $request->brand_id,
            'type_id' => $request->type_id
        ];
        $detail = [
            'price' => $request->price,
            'stock' => $request->stock,
            'description' => $request->description,
            'product_image' => $request->product_image
        ];
        if ($request->hasFile('product_image')) {
            if ($request->old_product_image) {
                Storage::delete($request->old_product_image);
            }
            $detail['product_image'] = $request->file('product_image')->store('product-image');
        } else {
            if ($product->find($product->id)->detail->product_image === 'product-image/NoImg.png') {
                $detail['product_image'] = 'product-image/NoImg.png';
            } else {
                $detail['product_image'] = $product->find($product->id)->detail->product_image;
            }
        };
        $product->find($product->id)->update($data);
        ProductDetails::find($product->id)->update([
            'price' => $request->price,
            'stock' => $request->stock,
            'description' => $request->description,
            'product_image' => $detail['product_image']
        ]);
        return redirect(route('product.index'))->with('success', 'Successfully Update Product');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product, ProductDetails $productDetails, ProductColorDetailsPivot $productColorDetailsPivot)
    {
        $deletes = $productColorDetailsPivot->where('product_id', '=', $product->id)->get();
        if ($product->find($product->id)->detail->product_image !== 'product-image/NoImg.png') {
            Storage::delete($product->find($product->id)->detail->product_image);
        };
        $product->find($product->id)->delete();
        $productDetails->find($product->id)->delete();
        foreach ($deletes as $delete) {
            $delete->delete();
        };
        return redirect(route('product.index'))->with('success', 'Successfuly Delete a Product');
    }
}

resources/views/admin/product/form.blade.php
@extends('admin.layouts.app')
@section('title')
    {{ @$product ? 'Update Product' : 'Add Product' }}
@endsection
@section('product', 'active')
@section('content')
    <div class="app-content content ">
        <div class="content-overlay"></div>
        <div class="header-navbar-shadow"></div>
        <div class="content-wrapper">
            <div class="content-header row">
                <div class="content-header-left col-md-9 col-12 mb-2">
                    <div class="row breadcrumbs-top">
                        <div class="col-12">
                            <h2 class="content-header-title float-left mb-0">Product Data</h2>
                            <div class="breadcrumb-wrapper">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="{{route('product.index')}}">List</a>
                                    </li>
                                    <li class="breadcrumb-item active">{{(@$product ? ' Update' : 'Add')}} Product
                                    </li>
                                </ol>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content-body">
                <!-- Basic Tables start -->
                <section id="basic-vertical-layouts">
                    <div class="row">
                        <div class=" col-12">
                            <div class="card">
                                <div class="card-body">
                                    @if ($errors->any())
                                        <div class="alert alert-danger" role="alert">
                                            <h4 class="alert-heading">Error!</h4>
                                            <div class="alert-body">
                                                <ul>
                                                    @foreach ($errors->all() as $error)
                                                        <li>{{ $error }}</li>
                                                    @endforeach
                                                </ul>
                                            </div>
                                        </div>
                                    @endif
                                    <form class="form form-vertical" id="form"  action="{{@$product ? route('product.update', $product) : route('product.store')}}"
                                          method="POST" enctype="multipart/form-data">
                                        @csrf
                                        @if(@$product)
                                            @method('PUT')
                                        @endif
                                        <div class="row">
                                            <div class="col-12">
                                                <div class="form-group">
                                                    <label for="product_name">Product Name</label>
                                                    <input type="text" id="produk" class="form-control" name="product_name" placeholder="Product Name"
                                                           value="{{old('product_name', @$product ? $product->product_name : '')}}"/>
                                                </div>
                                            </div>
                                            <div class="col-12">
                                                <div class="form-group">
                                                    <label for="type">Type</label>
                                                    <select class="form-select form-control" id="type" name="type_id" >
                                                        <option value="">- Select Product Type -</option>
                                                        @foreach($types as $type) 
                                                            <option value="{{$type->id}}" {{@$product && $product->type->id == $type->id ? 'selected' : '' }}>{{$type->type}}</option>
                                                        @endforeach
                                                    </select>
                                                </div>
                                            </div>
                                            <div class="col-12">
                                                <div class="form-group">
                                                    <label for="brand">Brand</label>
                                                    <select class="form-select form-control" id="brand" name="brand_id" >
                                                        <option value="">- Choose Product Brand -</option>
                                                        @foreach($brands as $brand)
                                                            <option value="{{$brand->id}}" {{@$product && $product->brand->id == $brand->id ? 'selected' : '' }}>{{$brand->brand_name}}</option>
                                                        @endforeach
                                                    </select>
                                                </div>
                                            </div>
                                            @if (@$product)

                                            @else
                                            <div class="col-12">
                                                <div class="form-group">
                                                    <label for="color">Color </label>
                                                    <select class="form-select form-control select2" multiple="multiple" id="color" name="color[]" >
                                                        @foreach ($colors as $color)
                                                            <option value="{{$color->id}}">
                                                                {{$color->color_name}}
                                                            </option>
                                                        @endforeach
                                                    </select>    
                                                    <p class="disabled">can't be edited, make sure you enter the color correctly</p>                                                   
                                                </div>
                                            </div>
                                            @endif
                                            <div class="col-12">
                                                <div class="form-group">
                                                    <label for="stock">Stock</label>
                                                    <input type="number" min="0" id="stock" class="form-control" name="stock" placeholder="10" value="{{old('stock', @$product ? $product->detail->stock : '')}}">
                                                </div>
                                            </div>
                                            <div class="col-12">
                                                <div class="form-group">
                                                    <label for="price">Price</label>
                                                    <input type="number" min="0" id="price" class="form-control" name="price" placeholder="100000"
                                                           value="{{old('price', @$product ? $product->detail->price : '')}}"/>
                                                </div>
                                            </div>
                                            <div class="col-12">
                                                    <div class="form-group">
                                                    <label for="description">Description</label>
                                                    <textarea type="text" class="form-control" name="description"> {{ @$product->detail->description }} </textarea> 
                                             </div>
                                                </div>
                                                
                                            <div class="col-12">
                                                <div class="form-group">
                                                    <label for="productDetails_image">Product Image</label>
                                                    @if (@$product)
                                                    <input type="hidden" name="old_product_image" value="{{ $product->detail->product_image }}">
                                                    @else
                                                    @endif
                                                    <input type="file" id="productDetails_image" class="form-control" name="product_image">
                                                </div>
                                            </div>
                                            <div class="col-12">
                                                <button type="submit" class="btn btn-primary mr-1">Submit</button>
                                                <a href="{{route('product.index')}}" type="reset" class="btn btn-outline-secondary">Cancel</a>
                                            </div>
                                        </div>
                                    </form>


                                </div>
                            </div>
                        </div>
                    </div>
                </section>
                <!-- Basic Tables end -->
            </div>
        </div>
    </div>

@endsection

@push('styles')
@endpush

@push('scripts')
    <script>
        $('.select2').select2();
    </script>
@endpush

resources/views/admin/product/list.blade.php
@extends('admin.layouts.app')

@section('title', 'Product')
@section('product', 'active')

@section('content')
<div class="app-content content ">
    <div class="content-overlay"></div>
    <div class="header-navbar-shadow"></div>
    <div class="content-wrapper">
        <div class="content-header row">
            <div class="content-header-left col-md-9 col-12 mb-2">
                <div class="row breadcrumbs-top">
                    <div class="col-12">
                        <h2 class="content-header-title float-left mb-0">Product Data</h2>
                        <div class="breadcrumb-wrapper">
                            <ol class="breadcrumb">
                                   {{-- <li class="breadcrumb-item"><a href="{{route('jenis.index')}}">jenis</a>
                                   </li> --}}
                                <li class="breadcrumb-item active">List
                                </li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="content-body">
            <div class="row" id="basic-table">
                @can('admin')
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <a href="{{route('product.create')}}" class="btn btn-primary waves-effect waves-float waves-light">Add Product</a>
                            </div>
                        </div>
                    </div>
                @endcan
            </div>
            <div class="d-flex justify-content-start">
                {{ $products->links() }}
            </div>
            <section id="card-demo-example">
                <div class="row match-height">
                    @foreach($products as $product)
                        <div class="col-md-4">
                            <div class="card">
                                <div class="card-body">
                                    <a href="{{route('product.show',$product)}}"><img class="card-img-top mb-2" src="{{ asset ('storage/' . $product->detail->product_image)}}" alt="Product Image"></a>
                                    <a href="{{route('product.show',$product)}}" class="h1"><h1 class="card-title font-weight-bolder">{{$product->product_name}}</h1></a>
                                    <p class="card-text">
                                        Price : Rp. {{number_format($product->detail->price,2)}}
                                    </p>
                                    <p class="card-text font-weight-bolder">Product Name : {{ $product->product_name }}</p>
                                    <p class="card-text font-weight-bolder">Product Type : {{ $product->type->type }}</p>
                                    <p class="card-text font-weight-bolder">Product Brand : {{ $product->brand->brand_name }}</p>
                                    <div class="d-flex">
                                        <div class="justify-content-end">
                                            <p class="card-text font-weight-bolder item-center">Product Color : 
                                                @foreach ($product->detail->color as $color) 
                                                    <abbr class="ml-1" title="{{ $color->color_name }}"><a class="box-color" style="background-color: {{ $color->color_hex }};"></a></abbr>
                                                @endforeach
                                            </p>
                                        </div>
                                    </div>
                                    <div class="mt-2">
                                        @can('admin')
                                        <a href="{{route('product.edit',$product)}}" class="btn btn-warning">Edit</a>
                                        <a type="button" data-id="{{ $product->id }}" class="btn del-btn btn-danger">Delete</a>
                                        @endcan
                                    </div>
                                    {{-- <a href="{{route('produk.show',$product->id)}}" class="btn btn-primary">View More</a> --}}
                                </div>
                            </div>
                        </div>
                        @endforeach
                    </div>
            </section>
        </div>
    </div>
</div>
@endsection

@push('styles')
<style>
    a.box-color{
        border-radius: 5px;
        padding: 2px;
        width: 20px;
        height: 20px;
        display: inline-block;
    }
</style>
@endpush

@push('script')

@if (session('success'))
{{-- <script>
    Swal.fire('Success','{{ session('success') }}','success')
</script> --}}
     <script>
         setTimeout(function () {
            toastr.success(
            '{{ session('success') }}',
            'Success!',
            {
                closeButton: true,
                tapToDismiss: true
            }
            );
        }, 1000);
     </script>
@endif

{{-- @if (session('success')) --}}
{{-- <script>
    Swal.fire('Success','{{ session('success') }}','success')
</script> --}}
     {{-- <script>
             setTimeout(function () {
                toastr.success(
                '{{ session('success') }}',
                'Success!',
                {
                    closeButton: true,
                    tapToDismiss: true
                }
                );
            }, 1000); 
     </script>
@endif --}}

@endpush
@push('scripts')
    <script>
        $(document).ready(function () {
            $(document).on('click', '.del-btn', function () {
                var id = $(this).data('id');
                const form = document.querySelector('.form');
                Swal.fire({
                    icon: 'error',
                    title: 'Are you sure?',
                    text: "You won't be able to revert this!",
                    type: 'error',
                    showCancelButton: true,
                    confirmButtonColor: '#28C76F',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Yes, delete it!'
                })
                    .then((result) => {
                        if (result.value) {
                            $.ajax({
                                'url': '{{url('product')}}/' + id,
                                'type': 'post',
                                'data': {
                                    '_method': 'DELETE',
                                    '_token': '{{csrf_token()}}'
                                },
                                success: function (response) {
                                    if (response == 1) {
                                        toastr.error('Data Gagal dihapus!', 'Gagal!', {
                                            closeButton: true,
                                            tapToDismiss: false
                                        });
                                        // location.reload();
                                    } else {
                                        toastr.success('Data Berhasil dihapus!', 'Berhasil!', {
                                            closeButton: true,
                                            tapToDismiss: false
                                        });
                                        // setTimeout(() => {
                                        //     location.reload();
                                        // }, 1500);
                                    }
                                }
                            });
                        } else {
                            console.log(`dialog was dismissed by ${result.dismiss}`)
                        }

                    });
            });

        });

    </script>
@endpush